name: typed_sql
version: 0.1.5
description: Package for doing SQL with some type safety.
homepage: https://github.com/google/dart-neats/tree/master/typed_sql
repository: https://github.com/google/dart-neats.git
issue_tracker: https://github.com/google/dart-neats/labels/pkg:typed_sql

environment:
  sdk: ^3.6.1

dependencies:
  analyzer: ^10.0.0
  build: '>=3.0.0 <5.0.0'
  code_builder: ^4.5.0
  collection: ^1.19.0
  convert: ^3.1.2
  glob: ^2.1.3
  meta: ^1.9.1
  mysql1: ^0.20.0
  postgres: ^3.5.4
  source_gen: ^4.0.0
  sqlite3: ^2.9.0

dev_dependencies:
  build_runner: ^2.1.9
  build_test: ^3.5.4
  build_verify: ^3.0.0
  checks: ^0.3.0
  dart_flutter_team_lints: ^3.3.0
  markdown: ^7.3.0
  matcher: ^0.12.18
  slugid: ^1.1.2
  test: ^1.21.0

resolution: workspace
