name: typed_sql
publish_to: none
description: Package for doing SQL with some type safety.

environment:
  sdk: ^3.6.1

dependencies:
  analyzer: ^7.2.0
  build: ^2.2.2
  code_builder: ^4.2.0
  collection: ^1.19.0
  glob: ^2.1.3
  meta: ^1.9.1
  postgres: ^3.5.4
  source_gen: ">=1.2.2 <3.0.0"
  sqlite3: ^2.7.2
  #build_config: ^1.0.0

dev_dependencies:
  build_runner: ^2.1.9
  build_verify: ^3.0.0
  dart_flutter_team_lints: ^3.3.0
  test: ^1.21.0
