name: pem
version: 1.0.0
description: |
  PEM encoding/decoding of textual keys following RFC 7468,
  supporting both lax/strict-mode, and certificates chains of concatenated
  PEM blocks.
homepage: https://github.com/google/dart-neats/tree/master/pem
repository: https://github.com/google/dart-neats.git
issue_tracker: https://github.com/google/dart-neats/labels/pkg:pem
dependencies:
  petitparser: ^2.1.1
dev_dependencies:
  test: ^1.5.1
  pedantic: ^1.4.0
environment:
  sdk: '>=2.0.0 <3.0.0'

