name: dart_neats_tool

# This should never be published it just locks the dev_dependencies for
# repository management, so they don't have to be installed globally.
publish_to: none

environment:
  sdk: '>=2.15.0 <3.0.0'

dev_dependencies:
  mono_repo: ^6.2.0
  pubspec_parse: ^1.2.0
