name: acyclic_steps
version: 0.11.0
description: |
  An explicit acyclic step dependency framework with concurrent evaluation
  and dependency injection.
homepage: https://github.com/google/dart-neats/tree/master/acyclic_steps
repository: https://github.com/google/dart-neats.git
issue_tracker: https://github.com/google/dart-neats/labels/pkg:acyclic_steps
dependencies:
  meta: ^1.1.7
dev_dependencies:
  test: ^1.5.1
  pedantic: ^1.4.0
environment:
  sdk: '>=2.12.0 <3.0.0'

