name: slugid
version: 1.0.0
description: |
  A URL-safe base64 encoding for UUIDv4 stripped of padding. Useful when
  embedding short random UUIDs in URLs.
homepage: https://github.com/google/dart-neats/tree/master/slugid½
repository: https://github.com/google/dart-neats.git
issue_tracker: https://github.com/google/dart-neats/labels/pkg:slugid½
dependencies:
  convert: ^2.0.2
dev_dependencies:
  test: ^1.5.1
  pedantic: ^1.4.0
environment:
  sdk: '>=2.0.0 <3.0.0'
