name: safe_url_check
version: 1.1.2
description: >-
  Check if an untrusted URL is broken, without allowing connections to a private
  IP address.
homepage: https://github.com/google/dart-neats/tree/master/safe_url_check
repository: https://github.com/google/dart-neats.git
issue_tracker: https://github.com/google/dart-neats/labels/pkg:safe_url_check
topics:
 - security
 - network

environment:
  sdk: ^3.5.0

dependencies:
  meta: ^1.11.0
  retry: ^3.0.0+1

dev_dependencies:
  test: ^1.5.1
  build_runner: ^2.3.3
  build_version: ^2.0.1

resolution: workspace
